### PR TITLE
upgraded to deno 0.42.0

### PR DESCRIPTION
**Pull request by halvardssm**

### CODE REVIEW

**Comment by siokas** [comment]
Nice! Thanks

**Comment by halvardssm** [comment]
No problem! Thank you for your work with this project!

**Comment by halvardssm** [comment]
Btw, could you make a new release for 0.42 compatability? I need it for my module 🙏

**Comment by halvardssm** [comment]
@siokas ^ 🙏

**Comment by siokas** [comment]
Done! https://github.com/siokas/denomander/releases/tag/0.5.1

**Comment by halvardssm** [comment]
Thanks! 👍

**Pull request merged**
